name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]
jobs:
  conditional:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
      - run: echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
      - run: mvn clean deploy --settings .maven-settings.xml -B -U -Prelease
        if: repo = alfasoftware/astra AND (branch = main OR tag IS present) AND NOT type = pull_request
    name: "Deploy"
