name: Publish package to the Maven Central Repository
on: 
  release:
    types: [edited]
jobs:
  release:
    name: "Deploy"
    runs-on: ubuntu-latest
    
    steps:
      - name: foo
        run: echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
      - name: bar
        run: echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
      - name: "Maven Deploy"
        run: mvn clean deploy --settings .maven-settings.xml -B -U -Prelease
