name: Publish package to the Maven Central Repository
on: 
 push:
#  release:
#    types: [edited]
jobs:
  release:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 11

#      - name: foo
#        run: echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
#      - name: bar
#        run: echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
      - name: "Maven Deploy"
        run: mvn clean deploy --settings .maven-settings.xml -B -U -Prelease
