name: Publish package to the Maven Central Repository
on: 
  release:
    types: [edited]
jobs:
  release:
    name: "Deploy"
    runs-on: ubuntu-latest
    
    steps:
      - name: "Maven Deploy"
        run: mvn clean deploy --settings .maven-settings.xml -B -U -Prelease
        env:
          GPG_OWNERTRUST: echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
          GPG_SECRET_KEYS: echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
